export const SET_LOADING = "APP/SET_LOADING";
export const SET_LOGIN_DIALOG = "APP/SET_LOGIN_DIALOG";
export const SET_EDIT_CONTRIBUTION = "APP/SET_EDIT_CONTRIBUTION"
export const SET_CONTRIBUTION_DIALOG = "APP/SET_CONTRIBUTION_DIALOG"